### ISSUE TITLE
Bench 3 query 6 has strange semantics

### ISSUE THREAD

**Issue by dcory** [crottyan/mgbench#2]
In bench 3 query 6, parts of the query is `CASE WHEN device_name LIKE 'coffee%' THEN event_value ELSE 0 END AS coffee`. This value is then averaged within each time bucket.

It's unlikely that an analytic scenario would want the average to include 0s for other devices. A better version would just be `CASE WHEN device_name LIKE 'coffee%' THEN event_value END AS coffee` which returns NULL for the other devices and does not affect the average.

**Comment by andrewcrotty** [comment]
Thanks for pointing this out. The original version of the query calculated hourly sums (hence `ELSE 0`) but was later switched to hourly averages instead without making this correction. I have updated the query as you suggested.
